<?php

declare(strict_types=1);

namespace App\Attaching\Migrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use Doctrine\Migrations\Exception\IrreversibleMigration;

final class Version20260818000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the canonical Attaching schema for clean PostgreSQL installations while remaining safe on existing installations';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'Attaching production schema requires PostgreSQL.');

        $hasAttachment = $schema->hasTable('attachment');
        $hasAttachmentLink = $schema->hasTable('attachment_link');

        if ($hasAttachment && $hasAttachmentLink) {
            return;
        }

        $this->abortIf($hasAttachment || $hasAttachmentLink, 'Attaching schema is partial; both attachment tables must exist together or both be absent.');

        $this->addSql(<<<'SQL'
CREATE TABLE attachment (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type varchar(255) NOT NULL,
    "mediaKind" varchar(255) DEFAULT NULL,
    "documentKind" varchar(255) DEFAULT NULL,
    "storageKind" varchar(255) NOT NULL,
    visibility varchar(255) NOT NULL,
    "originalName" varchar(255) NOT NULL,
    "storedName" varchar(255) NOT NULL,
    extension varchar(32) DEFAULT NULL,
    "mimeType" varchar(191) NOT NULL,
    size integer NOT NULL,
    checksum varchar(128) NOT NULL,
    "storagePath" varchar(1024) NOT NULL,
    title varchar(255) DEFAULT NULL,
    description text DEFAULT NULL,
    "altText" text DEFAULT NULL,
    width integer DEFAULT NULL,
    height integer DEFAULT NULL,
    "durationMs" integer DEFAULT NULL,
    "pageCount" integer DEFAULT NULL,
    "deletedAt" timestamp(0) without time zone DEFAULT NULL,
    uuid bytea NOT NULL,
    slug varchar(190) NOT NULL,
    first_title varchar(255) DEFAULT NULL,
    middle_title text DEFAULT NULL,
    last_title text DEFAULT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    modified_at timestamp(0) without time zone DEFAULT NULL,
    created_by varchar(190) DEFAULT NULL,
    modified_by varchar(190) DEFAULT NULL,
    active boolean NOT NULL DEFAULT true,
    enabled boolean NOT NULL DEFAULT true,
    status varchar(64) DEFAULT NULL
)
SQL);
        $this->addSql('CREATE UNIQUE INDEX "UNIQ_795FD9BBD17F50A6" ON attachment (uuid)');
        $this->addSql('CREATE UNIQUE INDEX "UNIQ_795FD9BB989D9B62" ON attachment (slug)');
        $this->addSql(<<<'SQL'
CREATE TABLE attachment_link (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ownerType" varchar(191) NOT NULL,
    "ownerId" varchar(191) NOT NULL,
    context varchar(191) DEFAULT NULL,
    slot varchar(191) DEFAULT NULL,
    position integer NOT NULL,
    "isPrimary" boolean NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    modified_at timestamp(0) without time zone DEFAULT NULL,
    created_by varchar(190) DEFAULT NULL,
    modified_by varchar(190) DEFAULT NULL,
    attachment_id integer NOT NULL,
    CONSTRAINT "FK_CEDF8DCE464E68B" FOREIGN KEY (attachment_id) REFERENCES attachment (id) ON DELETE CASCADE
)
SQL);
        $this->addSql('CREATE INDEX "IDX_CEDF8DCE464E68B" ON attachment_link (attachment_id)');
    }

    public function down(Schema $schema): void
    {
        throw new IrreversibleMigration('The canonical Attaching baseline is intentionally irreversible.');
    }
}
