parameters:
  attachment.storage.local.root_path: '%kernel.project_dir%/var/storage/attachment'
  attachment.upload.max_size: 33554432
  attachment.upload.allowed_media_mime_types:
    - image/jpeg
    - image/png
    - image/webp
    - image/gif
    - audio/mpeg
    - video/mp4
  attachment.upload.allowed_document_mime_types:
    - application/pdf
    - text/plain
    - application/msword
    - application/vnd.openxmlformats-officedocument.wordprocessingml.document
    - application/vnd.ms-excel
    - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    - application/vnd.ms-powerpoint
    - application/vnd.openxmlformats-officedocument.presentationml.presentation

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Contract\Attachment\AttachmentStorageInterface: '@App\Service\Storage\LocalAttachmentStorage'
  App\Contract\Attachment\AttachmentPathGeneratorInterface: '@App\Service\Attachment\AttachmentPathGenerator'
  App\Contract\Attachment\AttachmentChecksumGeneratorInterface: '@App\Service\Attachment\AttachmentChecksumGenerator'
  App\Contract\Attachment\AttachmentMimeTypeGuesserInterface: '@App\Service\Attachment\AttachmentMimeTypeGuesser'

  App\ServiceInterface\Attachment\AttachmentUploadServiceInterface: '@App\Service\Attachment\AttachmentUploadService'
  App\ServiceInterface\Attachment\AttachmentAttachServiceInterface: '@App\Service\Attachment\AttachmentAttachService'
  App\ServiceInterface\Attachment\AttachmentDetachServiceInterface: '@App\Service\Attachment\AttachmentDetachService'
  App\ServiceInterface\Attachment\AttachmentListServiceInterface: '@App\Service\Attachment\AttachmentListService'
  App\ServiceInterface\Attachment\AttachmentDownloadServiceInterface: '@App\Service\Attachment\AttachmentDownloadService'
  App\ServiceInterface\Attachment\AttachmentDeleteServiceInterface: '@App\Service\Attachment\AttachmentDeleteService'
  App\ServiceInterface\Attachment\AttachmentValidationServiceInterface: '@App\Service\Attachment\AttachmentValidationService'

  App\Service\Storage\LocalAttachmentStorage:
    arguments:
      $rootPath: '%attachment.storage.local.root_path%'

  App\Service\Attachment\AttachmentValidationService:
    arguments:
      $maxFileSizeInBytes: '%attachment.upload.max_size%'
      $allowedMediaMimeTypes: '%attachment.upload.allowed_media_mime_types%'
      $allowedDocumentMimeTypes: '%attachment.upload.allowed_document_mime_types%'
